apps/pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("shop/", views.ShopPageView.as_view(), name="shop"),
    path("cart/", views.CartPageView.as_view(), name="cart"),
    path("checkout/", views.CheckoutPageView.as_view(), name="checkout"),
    path("wishlist/", views.WishlistPageView.as_view(), name="wishlist"),
]

apps/products/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = "products"

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="shop", permanent=True)),
    path('compare/', views.compare_products, name='compare_products'),
    path('compare/add/<int:product_id>/', views.add_to_compare, name='add_to_compare'),
    path('compare/remove/<int:product_id>/', views.remove_from_compare, name='remove_from_compare'),

    path("<str:slug>/", views.ProductDetailView.as_view(), name="detail"),
    path("cart/<int:pk>/", views.CartView.as_view(), name="cart"),

    path("products/create/", views.product_create, name="create"),
    path("products/edit/<int:pk>/", views.product_edit, name="edit"),
    path("products/cateogry/create/", views.CategoryView.as_view(), name="create_category"),
    path("products/colors/create/", views.ProductColorsView.as_view(), name="create_color"),

    path("products/quick_view/<str:slug>/", views.product_detail_modal, name="quick_view")
]

apps/users/urls.py
from apps.users.views import UserDashboardView, UserOrdersView, UserOrderDetailView, UserOrderTrack, \
    UserOrderTrackDetail, UserProfileView, UserShopView
from django.urls import path

app_name = "users"

urlpatterns = [
    path("dashboard/", UserDashboardView.as_view(), name="dashboard"),
    path("orders/", UserOrdersView.as_view(), name="orders"),
    path("orders/<str:uuid>/", UserOrderDetailView.as_view(), name="order-detail"),
    path("orders-track/", UserOrderTrack.as_view(), name="order-track"),
    path("orders/track/<str:uuid>/", UserOrderTrackDetail.as_view(), name="order-track-detail"),
    path("profile/<int:pk>/", UserProfileView.as_view(), name="profile"),
    path("products/", UserShopView.as_view(), name="seller_products"),
]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from apps.pages.views import custom_400, custom_403, custom_404, custom_500

handler404 = custom_404
handler500 = custom_500
handler403 = custom_403
handler400 = custom_400

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.pages.urls")),
    path("accounts/", include("allauth.urls")),
    path("users/", include("apps.users.urls")),
    path("products/", include("apps.products.urls")),
    path("orders/", include("apps.orders.urls")),
    path("blogs/", include("apps.blogs.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
        path('api-auth/', include('rest_framework.urls')),
    ]

    if not settings.TESTING:
        from debug_toolbar.toolbar import debug_toolbar_urls

        urlpatterns += debug_toolbar_urls()

templates/base.html
{% load tailwind_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Islington Marketplace
        {% endblock %}
    </title>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet">

    <!-- Swiper JS -->
    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
    />

    <!-- noUISlider -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/nouislider@15.8.1/dist/nouislider.min.css"/>


    {% tailwind_css %}

    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>

    <link rel="icon" type="image/x-icon" href="{{ setting.favicon.url }}"/>

    <meta name="description" content="{% block meta_description %}{{ setting.meta_description }}{% endblock %}">

    {% block extra_css %}
    {% endblock %}

    <script type="module">
        if (!("anchorName" in document.documentElement.style)) {
            import("https://unpkg.com/@oddbird/css-anchor-positioning");
        }
    </script>
</head>
<body>
<div id="message-container">
    {% include "partials/messages.html" %}
</div>

<!-- Header -->
{% include "partials/header.html" %}

<main>
    {% block content %}
    {% endblock %}
</main>

<!-- Footer -->
{% include "partials/footer.html" %}

<!-- Swiper -->
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>

<!-- noUISlider -->
<script src="https://cdn.jsdelivr.net/npm/nouislider@15.8.1/dist/nouislider.min.js"></script>

<!-- HTMX -->
<script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.6/dist/htmx.min.js"
        integrity="sha384-Akqfrbj/HpNVo8k11SXBb6TlBWmXXlYQrCSqEWmyKJe+hDm3Z/B2WVG4smwBkRVm"
        crossorigin="anonymous"></script>

<script src="{% static 'js/script.js' %}"></script>

{% block extra_js %}
{% endblock %}

</body>
</html>

templates/dashboard_base.html
{% extends "base.html" %}
{% load static %}
{% load currency %}

{% block title %}Islington Marketplace - User Dashboard{% endblock %}

{% block content %}
    <section class="section-with-breadcrumb dashboard-wrappper">
        {% include "partials/breadcrumb.html" %}

        <div class="container mx-auto mt-10 mb-18 grid grid-cols-4 gap-18">
            <div class="col-span-1">
                <ul class="list bg-[var(--clr-gray-00)] shadow-[0px_8px_40px_rgba(0_0_0_0.8)] border border-[var(--clr-gray-100)] rounded-sm backdrop-blur-md py-4">
                    <li>
                        <a href="{% url 'users:dashboard' %}"
                           class="flex gap-3 dash-nav-link py-2.5 px-6 text-[var(--clr-gray-600)] text-sm items-center {% if active_nav == "dashboard" %}active-nav{% endif %}"
                           style="--nav-img-url: url('{% static 'images/icons/Stack.svg' %}'); --img-clr: var(--clr-gray-700);">
                            <div class="nav-icon"></div>
                            Dashboard
                        </a>
                    </li>
                    {% if request.user.user_type == "seller" %}
                        <li>
                            <a href="{% url 'users:seller_products' %}"
                               class="flex gap-3 dash-nav-link py-2.5 px-6 text-[var(--clr-gray-600)] text-sm items-center {% if active_nav == "seller-products" %}active-nav{% endif %}"
                               style="--nav-img-url: url('{% static 'images/icons/Shop.svg' %}'); --img-clr: var(--clr-gray-700);">
                                <div class="nav-icon"></div>
                                My Shop
                            </a>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'users:orders' %}"
                           class="flex gap-3 dash-nav-link py-2.5 px-6 text-[var(--clr-gray-600)] text-sm items-center {% if active_nav == "order-history" %}active-nav{% endif %}"
                           style="--nav-img-url: url('{% static 'images/icons/Storefront.svg' %}'); --img-clr: var(--clr-gray-700);">
                            <div class="nav-icon"></div>
                            Order History
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'users:order-track' %}"
                           class="flex gap-3 dash-nav-link py-2.5 px-6 text-[var(--clr-gray-600)] text-sm items-center {% if active_nav == "track-order" %}active-nav{% endif %}"
                           style="--nav-img-url: url('{% static 'images/icons/MapPinLine.svg' %}'); --img-clr: var(--clr-gray-700);">
                            <div class="nav-icon"></div>
                            Track Order
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'pages:cart' %}"
                           class="flex gap-3 dash-nav-link py-2.5 px-6 text-[var(--clr-gray-600)] text-sm items-center {% if active_nav == "shopping-cart" %}active-nav{% endif %}"
                           style="--nav-img-url: url('{% static 'images/icons/Cart.svg' %}'); --img-clr: var(--clr-gray-700);">
                            <div class="nav-icon"></div>
                            Shopping Cart
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'products:compare_products' %}"
                           class="flex gap-3 dash-nav-link py-2.5 px-6 text-[var(--clr-gray-600)] text-sm items-center {% if active_nav == "compare" %}active-nav{% endif %}"
                           style="--nav-img-url: url('{% static 'images/icons/ArrowsCounterClockwise.svg' %}'); --img-clr: var(--clr-gray-700);">
                            <div class="nav-icon"></div>
                            Compare
                        </a>
                    </li>
                    {#                    <li>#}
                    {#                        <a href=""#}
                    {#                           class="flex gap-3 dash-nav-link py-2.5 px-6 text-[var(--clr-gray-600)] text-sm items-center {% if active_nav == "addresses" %}active-nav{% endif %}"#}
                    {#                           style="--nav-img-url: url('{% static 'images/icons/Notebook.svg' %}'); --img-clr: var(--clr-gray-700);">#}
                    {#                            <div class="nav-icon"></div>#}
                    {#                            Addresses#}
                    {#                        </a>#}
                    {#                    </li>#}
                    <li>
                        <a href="{% url 'users:profile' request.user.pk %}"
                           class="flex gap-3 dash-nav-link py-2.5 px-6 text-[var(--clr-gray-600)] text-sm items-center {% if active_nav == "settings" %}active-nav{% endif %}"
                           style="--nav-img-url: url('{% static 'images/icons/Gear.svg' %}'); --img-clr: var(--clr-gray-700);">
                            <div class="nav-icon"></div>
                            Settings
                        </a>
                    </li>
                    <li>
                        <a href=""
                           class="flex gap-3 dash-nav-link py-2.5 px-6 text-[var(--clr-gray-600)] text-sm items-center"
                           style="--nav-img-url: url('{% static 'images/icons/SignOut.svg' %}'); --img-clr: var(--clr-gray-700);">
                            <div class="nav-icon"></div>
                            Logout
                        </a>
                    </li>
                </ul>
            </div>

            <div class="col-span-3" id="content">
                {% block dashboard_content %}
                {% endblock %}
            </div>
        </div>
    </section>
{% endblock %}